news/urls.py
from django.urls import path
from .views import NewsDetailView, NewsListView, add_event_to_calendar

app_name = "news"

urlpatterns = [
    path('<slug>/', NewsDetailView.as_view(), name="detail"),
    path('', NewsListView.as_view(), name='list'),
    path('dodaj-do-kalendarza/<pk>', add_event_to_calendar, name='add_to_calendar'),
]

newsletter/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = "newsletter"

urlpatterns = [
    url(
        r"^ajax/send_newsletter_welcome/$",
        views.send_newsletter_welcome,
        name="send_newsletter_welcome",
    ),
    url(
        r"^newsletter_deactivate/(?P<uidb>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$",
        views.newsletter_deactivate,
        name="newsletter_deactivate",
    ),
    path(
        "ajax/message_details/<message_id>",
        views.NewsletterMessageDetailsView,
        name="message_details",
    ),
]

newsletter/models.py
from django.db import models
from django.core.mail import send_mail
from decouple import config
from django.template.loader import render_to_string
from ckeditor_uploader.fields import RichTextUploadingField

from core.models import TimestampedModel
from core.tokens import deactivate_newsletter_token
from django.utils.translation import gettext_lazy as _
from core.field_validators import check_if_less_than_200_words
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode


class NewsLetterCampaign(TimestampedModel):
    newsletter_name = models.CharField(_('Nazwa kampanii'), max_length=255, blank=False, null=False)
    message = models.ForeignKey(
        'newsletter.NewsletterMessage',
        on_delete=models.PROTECT,
    )

    @staticmethod
    def send_email(data, from_email=None):
        context = {'message': data.get('message_to_send').content}
        for user in data.get('users'):
            context['uid'] = urlsafe_base64_encode(force_bytes(user.pk)).decode()
            context['token'] = deactivate_newsletter_token.make_token(user)
            message = render_to_string('newsletter/newsletter_email.html', context=context)
            send_mail(data.get('message_to_send').title, message, from_email, [user.email], html_message=message)


class NewsletterMessage(models.Model):
    title = models.CharField(_('Tytuł wiadomości'), max_length=100, blank=False, null=False)
    content = RichTextUploadingField(validators=[check_if_less_than_200_words])

    class Meta:
        verbose_name = _("Wiadomość")
        verbose_name_plural = _("Wiadomości")

    def __str__(self):
        return self.title

newsletter/views.py
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponseRedirect, HttpResponse
from django.http import JsonResponse
from django.shortcuts import redirect

from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.views.decorators.csrf import csrf_exempt

from core.tokens import deactivate_newsletter_token
from django.core.mail import send_mail
from decouple import config
from django.contrib.auth.models import User
from core.models import CustomUser
from newsletter.models import NewsletterMessage


@csrf_exempt
def send_newsletter_welcome(request):
    if request.method == "POST":
        if request.user.id:
            auth_user = request.user
            auth_user.is_subscriber = True
            auth_user.save()

            message = render_to_string(
                "newsletter/welcome.html",
                {
                    "user": auth_user,
                    "domain": get_current_site(request).domain,
                    "uid": urlsafe_base64_encode(force_bytes(auth_user.pk)).decode(),
                    "token": deactivate_newsletter_token.make_token(auth_user),
                },
            )
            mail_subject = "Dziękujemy za zapisanie się do naszego Newslettera"

            send_mail(
                mail_subject,
                message,
                config("EMAIL_HOST_USER"),
                [auth_user.email],
                html_message=message,
            )

            # Wyślij zmienną 'status' żeby usunąć przycisk 'Zapisz do newslettera'
            data = {"status": "success"}
        else:
            data = {"status": "failure"}
        return JsonResponse(data)
    else:
        return redirect("/")


def newsletter_deactivate(request, uidb, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb))
        user = CustomUser.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and deactivate_newsletter_token.check_token(user, token):
        custom_user = CustomUser.objects.get(pk=user.pk)
        custom_user.is_subscriber = False
        custom_user.save()
    return HttpResponseRedirect("/")


def NewsletterMessageDetailsView(request, message_id):
    message = NewsletterMessage.objects.get(id=message_id)

    return HttpResponse(message.content)

newsletter/templates/newsletter/newsletter_email.html
{% load customuser_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="pl">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title></title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap" rel="stylesheet">
</head>

<body>
    <div style="font-family: 'Lato', sans-serif; color:#575757; font-size:16px; font-weight:400; line-height:25px">
{% block message %}
    {{ message|add_domain_name_to_img_src|safe }}
    </div>
    <div style="margin-top:40px; font-family: 'Lato', sans-serif; text-align:left">
        <p style="font-weight:700; font-size:23px; font-weight:700; color:#575757; margin-bottom:0px; ">Marta Mularska</p>
        <p style="font-weight:400; font-size:16px; font-weight:400; color:#979797; margin-top:5px; ">M: +48 608 683 570</p>
        <hr style="width:220px; border-top: 1px solid #DEDEDE; display:inline-block; border-left:0px; margin-bottom:20px">
        <img src="https://sciezkidozdrowia.pl{% static 'gfx/sciezki_zdrowia_logo.png' %}" alt="Ścieżki Zdrowia - logo" style="display:block" />
        <p style="font-weight:700; font-size:23px; font-weight:700; color:#575757; margin-bottom:0px; display:block">Ścieżki Zdrowia Sp. z o.o.</p>
        <p style="font-weight:400; font-size:16px; font-weight:400; color:#979797; margin-top:5px; line-height:22px;">ul. B. Limanowskiego 5/4<br>33-100 Tarnów</p>
        <a href="https://sciezkidozdrowia.pl{% url 'newsletter:newsletter_deactivate' uidb=uid token=token %}" style="font-weight:400; font-size:16px; font-weight:400; color:#979797; margin-top:5px; line-height:22px;">Zrezygnuj z newslettera</p>
    </div>
{% endblock %}
</body>
</html>

newsletter/templates/newsletter/welcome.html
{% extends 'newsletter/newsletter_email.html' %}
{% block message %}
Dziękujemy za zapisanie się do naszego Newslettera {{ user.first_name }} !

Jeżeli chcesz zrezygnować z newsletter'a kliknij w link: <a href="http://{{ domain }}{% url 'newsletter:newsletter_deactivate' uidb=uid token=token %}">zrezygnuj z newslettera</a>

{% endblock %}