news/urls.py
from django.urls import path
from .views import NewsDetailView, NewsListView, add_event_to_calendar

app_name = "news"

urlpatterns = [
    path('<slug>/', NewsDetailView.as_view(), name="detail"),
    path('', NewsListView.as_view(), name='list'),
    path('dodaj-do-kalendarza/<pk>', add_event_to_calendar, name='add_to_calendar'),
]

profiles/urls.py
from django.urls import path

from profiles.views import CustomUserUpdateView, EventUpdateView, EventListView, ticket_create_view, TicketUpdateView, \
    ReservationCreateView, ReservationUpdateView, event_delete_view, NoteListView, NoteUpdateView, NoteCreateView, \
    user_profile_view, user_activate, NoteDetailView, BankAccountCreateView, BankAccountListView, \
    BankAccountUpdateView, event_create_view, NoteUserUpdateView

app_name = "profile"

urlpatterns = [

    path('<int:pk>/zaktualizuj/', CustomUserUpdateView.as_view(), name='update'),
    path('aktywacja/<uidb64>/<token>/', user_activate, name='activate'),

    path('notatki/', NoteListView.as_view(), name='note-list'),
    path('notatki/stworz', NoteCreateView.as_view(), name='note-create'),
    path('notatki/edytuj/<pk>', NoteUpdateView.as_view(), name='note-edit'),
    path('notatki/edytuj_p/<pk>', NoteUserUpdateView.as_view(), name='note-user-edit'),
    path('notatki/<pk>', NoteDetailView.as_view(), name='note-detail'),

    path('lista-eventow/', EventListView.as_view(), name='event-list'),  # UWAGA hardcode w widoku aktualizacji biletu
    path('stworz-event/', event_create_view, name='event-create'),
    path('edytuj-event/<pk>', EventUpdateView.as_view(), name='event-edit'),

    path('lista-kont/', BankAccountListView.as_view(), name='bankaccount-list'),  # UWAGA hardcode w widoku aktualizacji biletu
    path('stworz-konto/', BankAccountCreateView.as_view(), name='bankaccount-create'),
    path('edytuj-konto/<pk>', BankAccountUpdateView.as_view(), name='bankaccount-edit'),

    path('stworz-bilet/<pk>', ticket_create_view, name='ticket-create'),  # PK eventu
    path('edytuj-bilet/<pk>', TicketUpdateView.as_view(), name='ticket-edit'),  # PK biletu
    path('usun-bilet/<pk>', event_delete_view, name='ticket-delete'),  # PK biletu

    path('stworz-rezerwacje/<pk>', ReservationCreateView.as_view(), name='reservation-create'),  # PK biletu
    path('edytuj-rezerwacje/<pk>', ReservationUpdateView.as_view(), name='reservation-edit'),  # PK rezerwacji

    path('', user_profile_view, name='user-profile'),

]

news/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

from articles.utils import unique_slug_generator
from core.models import TimestampedModel, LocationModel, CustomUser
from profiles.models import BankAccount

from core.utils import get_or_none


def rl_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


class NewsCategory(models.Model):
    name = models.CharField(max_length=255, default=_('Bez kategorii'))
    description = models.TextField(default='', blank=True, null=True)
    slug = models.SlugField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-name']
        verbose_name = _("kategoria news'a")
        verbose_name_plural = _("kategorie news'ów")


pre_save.connect(rl_pre_save_receiver, sender=NewsCategory)


class News(models.Model):
    img = models.ImageField(_("Obraz promocyjny"), default='avatar/No-image-available.jpg', upload_to='products/',
                            blank=True, null=True)
    name = models.CharField(_("Nazwa eventu"), max_length=200)
    timestamp = models.DateTimeField(auto_now_add=True)
    description = RichTextUploadingField(_("Opis"))
    category = models.ForeignKey(NewsCategory, verbose_name=_("Kategoria"), on_delete=models.CASCADE)
    slug = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('news:detail', kwargs={"slug": self.slug})

    class Meta:
        ordering = ["-timestamp", "-name"]
        verbose_name = "news"
        verbose_name_plural = "newsy"


pre_save.connect(rl_pre_save_receiver, sender=News)


class Event2(TimestampedModel, LocationModel):
    img = models.ImageField(_("Zdjęcie"), default='avatar/No-image-available.jpg', upload_to='products/', blank=True,
                            null=True)
    speaker = models.CharField(_('Prowadzący'), max_length=255, blank=True, null=True)
    name = models.CharField(_('Nazwa eventu'), default=_("Podaj nazwę eventu"), max_length=255, blank=False, null=False)
    slug = models.CharField(max_length=255, blank=False, null=False)
    event_date = models.DateField(_('Data eventu'), blank=False, null=False)
    event_time = models.TimeField(_('Godzina rozpoczęcia eventu'), blank=False, null=False)
    description = RichTextUploadingField(_('Opis eventu'))
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_("Użytkownik"), related_name='events',
                                   blank=True, null=True, on_delete=models.SET_NULL)
    bank_account = models.ForeignKey(BankAccount, verbose_name=_("Konto bankowe"), blank=True, null=True, on_delete=models.DO_NOTHING)

    class Meta:
        verbose_name = "event"
        verbose_name_plural = "eventy"

    def get_absolute_url(self):
        return reverse('events:detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.name

    def is_added_to_calendar(self, user):
        ev = get_or_none(EventUser, **{'event': self, 'user': user})
        return bool(ev)


pre_save.connect(rl_pre_save_receiver, sender=Event2)


class Ticket(TimestampedModel):
    event = models.ForeignKey(Event2, verbose_name=_("Wydarzenie"), on_delete=models.CASCADE, blank=True, null=True,
                              related_name='tickets')
    price = models.IntegerField(_("Cena biletu"))
    currency = models.CharField(_("Waluta biletu"), default='PLN', max_length=30)
    quantity = models.IntegerField(_("Ilość biletów"))
    max_reservation = models.IntegerField(_("Maksymalna ilość biletów na zamówienie"), default=5)

    def __str__(self):
        return self.event.name


class Reservation(TimestampedModel):
    ticket = models.ForeignKey(Ticket, verbose_name=_("Rezerwacja"), on_delete=models.CASCADE, blank=True, null=True,
                               related_name='reservations')
    people_no = models.IntegerField(_("Ilość osób dla rezerwacji"))
    bought_by = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_("Użytkownik"), on_delete=models.CASCADE,
                                  blank=True, null=True)
    email = models.EmailField(_("Adres email"), blank=True, null=True)
    tel_no = models.CharField(_("Numer telefonu"), blank=True, null=True, max_length=15)
    ip = models.GenericIPAddressField(blank=True, null=True)
    first_name = models.CharField(_("Imię"), blank=True, null=True, max_length=100)
    last_name = models.CharField(_("Nazwisko"), blank=True, null=True, max_length=100)

    def __str__(self):
        return 'Rezerwacja na ' + self.ticket.event.name

    def get_absolute_url(self):
        return reverse('events:detail', kwargs={'slug': self.ticket.event.slug})


class EventUser(TimestampedModel):
    event = models.ForeignKey(Event2, blank=False, null=False, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=False, null=False, on_delete=models.CASCADE)

news/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext as _

from news.models import Event2, Ticket, Reservation
from core.models import CustomUser
from profiles.models import BankAccount


class CustomDateInput(forms.DateInput):
    input_type = 'date'


class CustomTimeInput(forms.TimeInput):
    input_type = 'time'


class EventForm(forms.ModelForm):
    """Used in user profile to create new event"""

    def __init__(self, user=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['bank_account'].choices = [('', '--')]
        # TODO: KONIECZNY REFACOTRING
        if user and isinstance(user, CustomUser):
            if BankAccount.objects.filter(user=user):
                self.fields['bank_account'].choices.extend([(account.id, account.bank_name) for account in
                                                        BankAccount.objects.filter(user=user)])
        else:
            self.fields['bank_account'].choices = [(account.id, account.bank_name) for account in
                                                        BankAccount.objects.all()]

    class Meta:
        model = Event2
        # 'description musi być na końcu ze względu na forloop w event2_form.html
        fields = ['img', 'country', 'city', 'street', 'speaker', 'name', 'event_date', 'event_time', 'bank_account', 'description']
        widgets = {
            'event_time': CustomTimeInput(),
            'event_date': CustomDateInput()
        }


class TicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ['event', 'price', 'currency', 'quantity', 'max_reservation']


class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = ['ticket', 'people_no', 'first_name', 'last_name', 'tel_no', 'email']

    def clean(self):
        data = super().clean()
        if data.get('people_no', None) > data.get('ticket', None).max_reservation:
            raise ValidationError(_("Masymalna ilość osób na rezerwacji nie może przekroczyć {0}").
                                  format(data.get('ticket', None).max_reservation),
                                  code='invalid_people_no',)
        return self.cleaned_data

    def clean_email(self):
        email = self.cleaned_data['email']
        ticket = self.cleaned_data['ticket']
        res = Reservation.objects.filter(email=self.cleaned_data.get('email', None), ticket=ticket)
        if res:
            raise ValidationError(_("Rezerwacja na ten adres email już istnieje"), code='invalid')
        return email

news/views.py
import datetime
import json

from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import DetailView, ListView
from googleapiclient.discovery import build
from httplib2 import Http
from oauth2client import file, client, tools

from .models import News, Event2


class NewsDetailView(DetailView):
    queryset = News.objects.all()


class NewsListView(ListView):
    queryset = News.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['event_list'] = Event2.objects.filter(event_date__gte=datetime.date.today()).order_by('event_date')
        return context


class EventDetailView(DetailView):
    queryset = Event2.objects.all().prefetch_related('tickets')


def add_event_to_calendar(request, pk):
    from .models import EventUser
    if request.user.is_authenticated:
        obj, created = EventUser.objects.get_or_create(event_id=pk, user=request.user)
        if created:
            SCOPES = 'https://www.googleapis.com/auth/calendar'
            store = file.Storage('token_' + str(request.user.id) + '.json')
            creds = store.get()
            event = Event2.objects.get(pk=pk)
            later = event.event_time.replace(hour=event.event_time.hour + 1)
            if not creds or creds.invalid:
                flow = client.flow_from_clientsecrets('credentials.json', SCOPES)
                creds = tools.run_flow(flow, store)
            service = build('calendar', 'v3', http=creds.authorize(Http()))

            event_to_add = {
                "summary": str(event.name),
                "description": event.description,
                "start": {
                    "dateTime": event.event_date.strftime('%Y-%m-%dT') + event.event_time.strftime('%H:%M:%S') + 'Z',
                },
                "end": {
                    "dateTime": event.event_date.strftime('%Y-%m-%dT') + later.strftime('%H:%M:%S') + 'Z',
                }
            }
            event_to_add = json.dumps(event_to_add, indent=4, sort_keys=True, default=str)
            service.events().insert(calendarId='primary', body=json.loads(event_to_add)).execute()
    return redirect(reverse('news:list'))

news/templates/news/event2_detail.html
{% extends 'base.html' %}

{% load static %}
{% load news_tags %}
{% block head_title %}{{ block.super }} - {{ event2.name }}{% endblock %}

{% block meta_tags %}
    {{ block.super }}
    <meta property="og:title" content="{{ event2.name }}" />
    <meta property="og:description" content="{{ event2.description|truncatewords:6|striptags|safe }}" />
    <meta property="og:image" content="http://sciezkidozdrowia.pl{{ event2.img.url }}" />
{% endblock %}



{% block content %}

    <div class="container wow fadeIn" style="margin-top:150px; margin-bottom:200px; height:100%; " id="offer">
    	<div class="row">
{#            ZDJĘCIE EVENTU#}
    		<div class="col-md-3 text-right">
                <img class="img-fluid" src="{{ event2.img.url }}"
                 width="220" height="220">
    		</div>

{#            POLE Z OPISEM I PRZYCISKAMI#}
    		<div class="col-md-8 text-left" style="border:3px solid #58a314">
{#                OPIS#}
                <h1>{{ event2.name }}</h1>
                <h3 class="dates"><i class="fas fa-calendar fa-xs"></i> {{ event2.event_date }}</h3>
                <h3><i class="fas fa-clock fa-xs"></i> {{ event2.event_time }}</h3>

                {% if event2.city and event2.street %}
                    <h3 class="place"><i class="fas fa-map-marker fa-xs"></i>
                    {{ event2.city }} - {{ event2.street }}
                    </h3>
                {% elif event2.city or event2.street %}
                    <h3 class="place"><i class="fas fa-map-marker fa-xs"></i>
                    {{ event2.city|default_if_none:"" }}{{ event2.street|default_if_none:"" }}
                    </h3>
                {% endif %}
                <h3 class="dates"><i class="fas fa-microphone fa-xs"></i>  {{ event2.speaker|default_if_none:"Mówca nieogłoszony" }}</h3>

                <span>{{ event2.description|safe }}</span>

{#                KONTO BANKOWE#}
                {% if event2.bank_account %}
                <h2>Dane do przelewu:</h2>
                <span>
                    <h3>{{ event2.bank_account.bank_name }}</h3>
                    <h3>{{ event2.bank_account.bank_number }}</h3>
                    {% if event2.bank_account.first_name and event2.bank_account.last_name %}
                        <h3>{{ event2.bank_account.first_name }} {{ event2.bank_account.last_name }}</h3>
                    {% else %}
                        <h3>{{ event2.user.first_name }} {{ event2.user.lasst_name }}</h3>
                    {% endif %}
                </span>
                {% endif %}

{#                BILETY#}
                <span>
                    <h2>Bilety:</h2>
                    {% for ticket in event2.tickets.all %}
                        <h3><b>
                        {% if ticket|get_reservation:request.user %}
                            {{ ticket.price }} {{ ticket.currency }} - pozostało {{ ticket.quantity }}
                            {% with ticket|get_reservation:request.user as reservation %}
                                <a href="{% url 'profile:reservation-edit' reservation.pk %}">Edytuj rezerwację</a>
                            {% endwith %}
                        {% else %}
                            {{ ticket.price }} {{ ticket.currency }} - pozostało {{ ticket.quantity }}
                            <a href="{% url 'profile:reservation-create' ticket.pk %}">Zarezerwuj</a>
                        {% endif %}
                    {% empty %}
                        Wstęp wolny, bez uprzedniej rejestracji
                        </b></h3>
                    {% endfor %}
                </span>

                <span>
                    <a href="{% url 'news:add_to_calendar' event2.pk %}" class="simple_link">Dodaj do kalendarza</a>
                    <a href="{{ request.META.HTTP_REFERER }}" class="simple_link">Powrót</a>

                    {% if user == event.created_by or user.is_staff %}
                        <a href="{% url 'profile:event-edit' event2.pk %}" class="simple_link">Edytuj</a>
                    {% endif %}
                </span>

            </div>
    	</div>
    </div>

{% endblock %}



{% block extra_js %}
    <script>
        var images = document.querySelectorAll('.text-left img');
        console.log(images);
        var count;
        for (count = 0; count < images.length; count++) {
            images[count].style.maxWidth = '100%';
            images[count].style.height = 'auto';
        }
    </script>
{% endblock %}

news/templates/news/event2_form.html
{% extends 'base.html' %}

{% block extra_style %}
    <style>
        table, td, th {border: 0 !important;}
    </style>
{% endblock %}

{% block content %}

    {{ view.get_field_names_anonymous_user }}
    <div class="container-fluid justify-content-center" style="margin-top: 100px;">
        <div class="text-center">
            <h2>Event</h2>
            <form method="POST" class="form-horizontal" enctype='multipart/form-data'>
            {{ form.media }}
            {% csrf_token %}
            <div class="justify-content-center">
            <table align="center">
            {% for field in form %}
                {% if not forloop.revcounter == 1  %}
                <tr>
                <td class="text-right">{{ field.label }}</td><td>{{ field }}</td>
                </tr>
                <tr><td colspan="2" class="form-error">{{ field.errors.as_text|cut:"* " }}</td></tr>
                {% else %}

                    </table>
                    </div>
                    <div class="row">
                    <div class="col-sm-12 col-md-10 offset-md-1">
                    {{ field.label }}
                    {{ field }}
                    </div>
                    </div>
                {% endif %}
            {% endfor %}

            <a href="{{ request.META.HTTP_REFERER }}" style="margin-top: 5px;" class="btn btn-666">Powrót</a>
            <button style="margin-top: 5px;" class="btn btn-666" type="submit">Zapisz</button>

            </form>
        </div>
    </div>
{% endblock %}

{% block extra_js %}
    {{ block.super }}
    <script>
    document.getElementById('id_img').classList.add('filestyle');
    document.getElementById('id_img').setAttribute('data-text', 'Wybierz zdjęcie')
    </script>
{% endblock %}

news/templates/news/event2_list.html
{% extends 'base.html' %}
{% load static %}
{% block extra_style %}
    <link rel="stylesheet" href="{% static 'css/delete_popup.css' %}">
{% endblock %}


{% block content %}

<script>
    function deletePopup(pk, del_type){
    // get the mPopup
    var mpopup = $('#mpopupBox');
    if (del_type == 'ticket'){
        mpopup = $('#mpopupBox2');
    }
    console.log(pk);
    var i;
    for (i = 0; i < document.querySelectorAll('input[name="pk"]').length; i++){
        document.querySelectorAll('input[name="pk"]')[i].value = pk;
        document.querySelectorAll('input[name="del_type"]')[i].value = del_type;
    }

    // open the mPopup
    mpopup.show();
    // close the mPopup once close element is clicked
    $(".close").on('click',function(){
        mpopup.hide();
    });

    // close the mPopup when user clicks outside of the box
    $(window).on('click', function(e) {
        if(e.target == mpopup[0]){
            mpopup.hide();
        }
    });
}

    function showReservations(res_id) {
        if (document.getElementById(res_id).style.display === 'none'){
            document.getElementById(res_id).style.display = 'block'
        }
        else {
            document.getElementById(res_id).style.display = 'none'
        }
    }
</script>


{#    MODALE#}
    <div id="mpopupBox" class="mpopup text-center">
        <!-- mPopup content -->
        <div class="mpopup-content">
            <div class="mpopup-head">
                <span class="close">×</span>
                <h2>Czy na pewno chcesz usunąć wydarzenie?</h2>
            </div>
            <div class="mpopup-main">
                <form method="post">
                    {% csrf_token %}
                    <p><input type="hidden" name="pk"/></p>
                    <p><input type="hidden" name="del_type"/></p>
                    <p><button class="btn btn-666" type="submit">USUŃ</button></p>
                </form>
            </div>
            <div class="mpopup-foot">
                <p>&nbsp;</p>
            </div>
        </div>
    </div>
    <div id="mpopupBox2" class="mpopup text-center">
        <!-- mPopup content -->
        <div class="mpopup-content">
            <div class="mpopup-head">
                <span class="close">×</span>
                <h2>Czy na pewno chcesz usunąć bilet?</h2>
            </div>
            <div class="mpopup-main">
                <form method="post">
                    {% csrf_token %}
                    <p><input type="hidden" name="pk"/></p>
                    <p><input type="hidden" name="del_type"/></p>
                    <p><button class="btn btn-666" type="submit">USUŃ</button></p>
                </form>
            </div>
            <div class="mpopup-foot">
                <p>&nbsp;</p>
            </div>
        </div>
    </div>

<div class="container" style="margin-top: 87px">
    <div class="row">
        {% for event in object_list|dictsortreversed:'event_date' %}
            <div class="col-sm-12 col-md-4">
                <img src="{{ event.img.url }}" class="img-fluid" style="display: block; margin: auto;"
                width="220" height="220">
            </div>
            <div class="col-sm-12 col-md-8">
                <h1>{{ event.name }}</h1>
                <h3><i class="fa fa-calendar fa-xs"></i> {{ event.event_date }} - {{ event.event_time }} </h3>
                <h3><i class="fas fa-map-marker fa-xs"></i>{{ event.city|default:'Nie podano miasta' }}, {{ event.country|default:'Nie podano kraju' }}</h3>
                <h4>{{ event.speaker|default_if_none:'Nie podano mówcy' }}</h4>
                <p>{{ event.description|safe|striptags|truncatewords_html:20 }}</p>
                {% if event.tickets.all %}
                <h3>Bilety:</h3>
                {% for ticket in event.tickets.all %}
                    <div>
                    {{ ticket.price }} {{ ticket.currency}} - zostało {{ ticket.quantity }} sztuk
                    <a class="btn btn-666" href="{% url 'profile:ticket-edit' ticket.pk %}">Edytuj bilet</a>
                    <button class="btn btn-666" onclick="deletePopup('{{ ticket.pk }}', 'ticket')">Usuń bilet</button>
                    {% if ticket.reservations.all %}
                        <button class="btn btn-666" onclick="showReservations('res_{{ ticket.id }}')">Pokaż rezerwacje</button>
                        <div id="res_{{ ticket.id }}" style="display: none;">
                        <table style="margin-top: 5px; width: 100%;" class="text-center">
                            <tr>
                                <th class="text-center">Coral ID</th>
                                <th class="text-center">Email</th>
                                <th class="text-center">Imię</th>
                                <th class="text-center">Nazwisko</th>
                                <th class="text-center">Numer tel</th>
                                <th class="text-center">Ilość osób</th>
                            </tr>
                            {% for reservation in ticket.reservations.all %}
                                <tr>
                                    <td>{{ reservation.bought_by.coral_id|default_if_none:"-" }}</td>
                                    <td>{{ reservation.bought_by.email }} {{ reservation.email }}</td>
                                    <td>{{ reservation.bought_by.first_name|default_if_none:"-" }} {{ reservation.first_name }}</td>
                                    <td>{{ reservation.bought_by.last_name|default_if_none:"-" }}{{ reservation.last_name }}</td>
                                    <td>{{ reservation.bought_by.tel_no|default_if_none:"-" }}</td>
                                    <td>{{ reservation.people_no }}</td>
                                </tr>
                            {% endfor %}
                        </table>
                        </div>
                    {% endif %}
                    </div>
                    <br>
                {% endfor %}
                {% endif %}
                <div style="margin-top: 20px;">
                    <a class="btn btn-666" href="{% url 'profile:event-edit' event.pk %}">Edytuj</a>
                    <a class="btn btn-666" href="{% url 'profile:ticket-create' event.pk %}">Dodaj bilet</a>
                    <a class="btn btn-666" href="#" onclick="deletePopup('{{ event.pk }}', 'event')"
                        style="color:white !important; ">Usuń event</a>
                </div>
                <hr>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

news/templates/news/news_detail.html
{% extends 'base.html' %}
{% block head_title %}{{ block.super }} - {{ news.name }}{% endblock %}

{% block meta_tags %}
    {{ block.super }}
    <meta property="og:title" content="{{ news.name }}" />
    <meta property="og:description" content="{{ news.description|truncatewords:6|striptags|safe }}" />
    <meta property="og:image" content="http://sciezkidozdrowia.pl{{ news.img.url }}" />
{% endblock %}

{% block content %}
<div class="container" style="margin-top:150px">
	<div class="row justify-content-center">
        <div class="col-lg-11" >

            <blockquote class="blockquote wow fadeIn" >
                <img src="{{ news.img.url }}" class="img-fluid" style="display: block; margin: auto;"
                 width="220" height="220">
                <h1 class="text-center" style="color: green;">{{ news.name }}</h1><br>
                <p class="mb-0 text-justify">{{ news.description|safe }}</p>
                <a href="{{ request.META.HTTP_REFERER }}" class="see_more text-center">Powrót</a>
            </blockquote>

	    </div>
    </div>
</div>
{% endblock %}

news/templates/news/news_list.html
{% extends 'base.html' %}

{% block head_title %}Artykuły - {{ block.super }}{% endblock %}
{% block content %}<br><br>
<div class="container" style="margin-top: 5em; margin-bottom:200px; justify-content: center; ">
    <div class="row">
        <div class="col-md-4 text-center">
            <h1>Wydarzenia</h1>
                {% for event in event_list %}
                    <div class="col-12">
                    <div style=" background-image: url({{ event.img.url }}); margin:10px;">
                        <a href="{{ event.get_absolute_url }}" class="kafel  d-flex justify-content-center mt-xs-3 align-items-center"  >
                            <div class="content text-center">
                            <p class="dates"><i class="fas fa-calendar fa-xs"></i> {{ event.event_date }} <i class="fas fa-clock fa-xs"></i> {{ event.event_time }}</p>
                            <p class="place"><i class="fas fa-map-marker fa-xs"></i> {{ event.street }}</p>
                            <h1>{{ event.city }}</h1>
                            <p class="author">Prowadzący: {{ event.speaker }}</p>
                            </div>
                        </a>
                    </div>
                    </div>
                {% endfor %}
        </div>
        <div class="col-md-8 text-center">
            <h1>Aktualności</h1>
    	<div class="row" >
        {% for news in object_list %}
    		<div class="col-md-6 cell text-center">
    			<a href="{{ news.get_absolute_url }}"  class="hvr-glow">
                  	<div style="height: 63%; margin-top: -15px;">
    				<img class="img-fluid  wow fadeIn" src="{{ news.img.url }}"
                    width="220" height="220">
                  </div>
    				<h1 style="height: 18%;" class=" wow fadeIn">{{ news.name }}</h1>
                    <h3 style="height: 8%; margin-bottom: -10px;" class=" wow fadeIn">
                        {{ news.description|truncatewords:5|safe|linebreaks|striptags }}</h3>
    				<span style="height: 12%; margin-bottom: 2px;" class="wow fadeIn">Zobacz więcej</span>
    			</a>
    		</div>
            {% empty %}
            <p>puste!!!</p>
            {% endfor %}
  	    </div>
        </div>
    </div>
</div>
{% endblock %}

news/templates/news/reservation_success.html
Dziękujemy za rezerwację biletów na wydarzenie {{ reservation.ticket.event.name }}
Wydarzenie odbędzie się dnia {{ reservation.ticket.event.event_date }} {{ reservation.ticket.event.event_time }}, w mieście {{ reservation.ticket.event.city }}, {{ reservation.ticket.event.country }}


Ilość biletów: {{ reservation.people_no }}
Na nazwisko: {% if not reservation.bought_by %}{{ reservation.first_name }} {{ reservation.last_name }}{% else %}{{ reservation.user.first_name }} {{ reservation.user.last_name }}{% endif %}

Zespół Ścieżki Zdrowia.